USE GD1C2023
GO

IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'G_DE_GESTION')
BEGIN
	EXEC('CREATE SCHEMA G_DE_GESTION')
END
GO

--- asi se pueden buscar las tablas y despues eliminarlas
--- Es para poder ir testeando
IF OBJECT_ID('G_DE_GESTION.venta_cupon') IS NOT NULL DROP TABLE LOS_MAGIOS.venta_cupon
IF OBJECT_ID('G_DE_GESTION.venta_descuento') IS NOT NULL DROP TABLE LOS_MAGIOS.venta_descuento
IF OBJECT_ID('G_DE_GESTION.venta_producto') IS NOT NULL DROP TABLE LOS_MAGIOS.venta_producto
IF OBJECT_ID('G_DE_GESTION.tipo_envio_localidad') IS NOT NULL DROP TABLE LOS_MAGIOS.tipo_envio_localidad
IF OBJECT_ID('G_DE_GESTION.venta') IS NOT NULL DROP TABLE LOS_MAGIOS.venta
IF OBJECT_ID('G_DE_GESTION.envio') IS NOT NULL DROP TABLE LOS_MAGIOS.envio
IF OBJECT_ID('G_DE_GESTION.tipo_envio') IS NOT NULL DROP TABLE LOS_MAGIOS.tipo_envio
IF OBJECT_ID('G_DE_GESTION.compra_producto') IS NOT NULL DROP TABLE LOS_MAGIOS.compra_producto
IF OBJECT_ID('G_DE_GESTION.compra') IS NOT NULL DROP TABLE LOS_MAGIOS.compra
IF OBJECT_ID('G_DE_GESTION.proveedor') IS NOT NULL DROP TABLE LOS_MAGIOS.proveedor
IF OBJECT_ID('G_DE_GESTION.cliente') IS NOT NULL DROP TABLE LOS_MAGIOS.cliente
IF OBJECT_ID('G_DE_GESTION.localidad') IS NOT NULL DROP TABLE LOS_MAGIOS.localidad
IF OBJECT_ID('G_DE_GESTION.provincia') IS NOT NULL DROP TABLE LOS_MAGIOS.provincia
IF OBJECT_ID('G_DE_GESTION.producto') IS NOT NULL DROP TABLE LOS_MAGIOS.producto
IF OBJECT_ID('G_DE_GESTION.canal') IS NOT NULL DROP TABLE LOS_MAGIOS.canal
IF OBJECT_ID('G_DE_GESTION.tipo_canal') IS NOT NULL DROP TABLE LOS_MAGIOS.tipo_canal
IF OBJECT_ID('G_DE_GESTION.medio_pago') IS NOT NULL DROP TABLE LOS_MAGIOS.medio_pago
IF OBJECT_ID('G_DE_GESTION.tipo_descuento') IS NOT NULL DROP TABLE LOS_MAGIOS.tipo_descuento
IF OBJECT_ID('G_DE_GESTION.cupon') IS NOT NULL DROP TABLE LOS_MAGIOS.cupon
IF OBJECT_ID('G_DE_GESTION.categoria_producto') IS NOT NULL DROP TABLE LOS_MAGIOS.categoria_producto
IF OBJECT_ID('G_DE_GESTION.descuento_compra') IS NOT NULL DROP TABLE LOS_MAGIOS.descuento_compra
IF OBJECT_ID('G_DE_GESTION.variante') IS NOT NULL DROP TABLE LOS_MAGIOS.variante
IF OBJECT_ID('G_DE_GESTION.tipo_variante') IS NOT NULL DROP TABLE LOS_MAGIOS.tipo_variante
IF OBJECT_ID('G_DE_GESTION.tipo_medio_pago') IS NOT NULL DROP TABLE LOS_MAGIOS.tipo_medio_pago
GO




